import Head from "next/head";
import { Overpass } from "next/font/google";
import clsx from "clsx";
import { useCallback, useState } from "react";

const font = Overpass({
  subsets: ["latin-ext"],
});

export default function Home() {
  const [fetching, setFetching] = useState(false);
  const handleFetchfromBankingOA = useCallback(() => {
    setFetching(true);
    fetch("/api/nosetcookie", {
      credentials: "include",
    })
      .then((res) => res.json())
      .then((data) => {
        setFetching(false);
        console.log(data);
      });
  }, []);
  const handleFetchfromBanking = useCallback(() => {
    setFetching(true);
    fetch("https://banking.bluebuckdesigns.xyz/api/nosetcookie", {
      credentials: "include",
    })
      .then((res) => res.json())
      .then((data) => {
        setFetching(false);
        console.log(data);
      })
      .catch((err) => {
        setFetching(false);
        console.error(err);
      });
  }, []);
  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={clsx(font.className, "flex min-h-screen flex-col")}>
        <nav className="flex items-center bg-gray-500 px-20 py-4">
          <h2 className="text-xl font-semibold text-gray-100">
            OnlineAccess.EdwardJones.com
          </h2>
        </nav>
        <div className="grid grow place-items-center px-20">
          <div className="flex w-full flex-col">
            <div className="mb-8 flex gap-8">
              <button
                onClick={handleFetchfromBanking}
                className="rounded bg-teal-500 px-4 py-2 font-bold leading-relaxed text-white transition-colors hover:bg-teal-400 disabled:bg-gray-400 disabled:text-gray-200"
                disabled={fetching}
              >
                GET Call to Banking.Edwardjones.com and No Set-Cookie
              </button>
              <button
                onClick={handleFetchfromBankingOA}
                className="rounded bg-amber-500 px-4 py-2 font-bold leading-relaxed text-white transition-colors hover:bg-amber-400 disabled:bg-gray-400 disabled:text-gray-200"
                disabled={fetching}
              >
                GET Call to OnlineAccess.Edwardjones.com
              </button>
            </div>
            <div className="h-[65dvh] w-full rounded border shadow-md">
              <iframe
                src="https://banking.bluebuckdesigns.xyz"
                sandbox="allow-same-origin allow-scripts allow-popups allow-forms"
                className="h-full w-full rounded"
              ></iframe>
            </div>
          </div>
        </div>
      </main>
    </>
  );
}
